const text = [
  `Soft fluffy pancakes with syrup pair well with crispy bacon and eggs. Freshly baked bread with butter complements a warm hearty soup on chilly days. Sweet juicy strawberries blend smoothly into yogurt. Crunchy granola with almonds tops a creamy parfait nicely. Fluffy scrambled eggs with toast and jam make a simple breakfast into something tasty. Warm blueberry muffins with coffee bring comfort. Oatmeal with honey and raisins warms you up. Grilled cheese sandwiches with tomato soup satisfy hunger. A slice of apple pie with whipped cream ends meals sweetly. Fruit smoothies refresh on hot days. Chocolate chip cookies tempt everyone.`,
  `Modern life moves fast with tech shaping daily routines, from apps organizing tasks to sleek gadgets in homes. Online shops offer endless choices, delivering goods fast while cafes brew artisanal coffee for busy folks. Quiet parks provide calm amidst bustling streets, perfect for a quick break or a thoughtful stroll before work resumes. People juggle jobs and hobbies, chasing balance in a world that’s always on, sipping trendy drinks like matcha or iced lattes while planning their next move.`,
  `Dark stormy nights bring howling winds, rattling windows as rain taps the roof steadily. Thunder rumbles low, shaking the ground while lightning flashes bright across the sky briefly. Restless dogs pace indoors, whining softly, sensing something wild outside beyond their cozy walls. Shadows dance on floors from flickering lights, painting eerie shapes. Power cuts plunge homes into silence, save for the storm’s chorus, urging folks to huddle close until dawn breaks calm and clear again.`,
  `Dog barks at mailman daily, chasing tires down the street with boundless energy always. Squirrels taunt from branches, dodging fluffy paws as he leaps and misses every time. Toys pile up in corners, chewed to bits—proud trophies of playful chaos indoors. Naps stretch long on sunny rugs, then sudden zooms erupt, knocking over lamps. Begging eyes lock on dinner plates, scoring scraps before bounding off to dig holes in the yard endlessly.`,
  `This movie’s plot twists confuse yet thrill! The dialogue’s sharp but loud characters shout their emotions too much. Costumes dazzle, pulling you into wild scenes like racing through a jungle alive with sound. She warned him—danger loomed close! He ignored it, chasing glory, you fool! Critics might pan the pacing, but I cheer its bold mess. The villain’s laugh echoes long after credits roll, haunting dreams with that sly grin of his.`,
  `Fresh ripe tomatoes burst with flavor. Grilled steak sizzles hot, seasoned lightly with salt and pepper perfectly. Warm baked potatoes with butter melt in your mouth smoothly. Crisp green salads with vinaigrette refresh the palate nicely. Spicy chili simmers low, filling rooms with hearty aromas everyone craves. Sweet corn on the cob shines golden. Creamy mashed cauliflower pairs well with roasted chicken cleanly.`,
  `Bright sunny hills bloom with wildflowers, bees hum lazily over petals all day long. Rivers wind slow through valleys, reflecting blue skies as fish dart below quietly. Old barns stand weathered, holding stories of harvests past while tractors hum nearby now. Dusty trails call hikers to roam free, breathing crisp air under tall pines, finding peace in simple steps away from city noise completely.`,
  `Warm cozy sweaters wrap you up tight, perfect for chilly walks with steaming mugs in hand. Crackling fires glow bright, casting light on books read slow by night quietly. Soft blankets pile high on couches, tempting naps as rain taps windows gently outside. Fresh pine scents drift in, mixing with baked bread aromas wafting from ovens daily. Candlelight flickers soft, painting walls with calm while winter settles in fully.`,
  `Sailors mend nets by dawn’s light, gulls cry overhead circling weathered docks steadily. Waves crash hard on rocky shores, spraying salt as boats bob in harbor safely. Fish haul in heavy, scales glinting silver under sun while ropes creak taut against wind. Lanterns sway dim at night, guiding crews home through fog with faint beams cutting dark clearly.`,
];
export default text;
